#include $(PRO_ROOT_PATH)/mkrules/rules.mk
include $(PRO_ROOT_PATH)/mkrules/header.mk


#LIBS+=$(LIB_BASE_DIR)/$(MODULE)/$(MODULE).a

INCLUDE += -I$(PRO_ROOT_PATH)/app/$(MODULE)/include

include $(PRO_ROOT_PATH)/mkrules/footer.mk
